In [1]:
import pandas as pd
from datetime import datetime

In [2]:
#Read out csv that we saved in parse_data
#Csv has two rows for each game, since it has one for perspective of each team
#(i.e. one where team is ATL, opp_team is DET and next where team is DET, opp_team is ATL)
df = pd.read_csv("nba_games.csv", index_col=0)

In [3]:
df = df.sort_values("date")

In [4]:
df = df.reset_index(drop=True)

In [5]:
#Delete extra columns
del df["index_opp"]

In [6]:
df["team"]

0        DET
1        ATL
2        CLE
3        CHI
4        NOP
        ...
25491    CHO
25492    ATL
25493    ORL
25494    MEM
25495    SAS
Name: team, Length: 25496, dtype: object

In [7]:
df = df.copy()
# Group dataframe by team, then apply the function to that team's next game (instead of some other random team by date)
df['target'] = df.groupby('team')['won'].shift(-1) # Target will be be false if team lost next game, true if they won

In [8]:
# Last row (most recent game for that team) now has NaN since there's no next game to read
df[df["team"] == "WAS"]

,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
8,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,0.600,15.0,...,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True,True
51,35.0,68.0,0.515,12.0,21.0,0.571,36.0,44.0,0.818,8.0,...,32.4,138.0,122.0,MIL,113,1,2016,2015-10-30,True,False
64,38.0,90.0,0.422,6.0,22.0,0.273,28.0,33.0,0.848,11.0,...,28.7,153.0,108.0,NYK,117,0,2016,2015-10-31,False,True
124,42.0,87.0,0.483,8.0,23.0,0.348,10.0,14.0,0.714,4.0,...,30.0,160.0,109.0,SAS,99,0,2016,2015-11-04,True,False
166,36.0,88.0,0.409,8.0,25.0,0.320,18.0,23.0,0.783,10.0,...,41.6,146.0,103.0,BOS,118,1,2016,2015-11-06,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25378,35.0,86.0,0.407,12.0,45.0,0.267,8.0,10.0,0.800,11.0,...,26.9,208.0,112.0,BOS,124,1,2025,2025-04-06,False,False
25396,38.0,91.0,0.418,11.0,39.0,0.282,11.0,15.0,0.733,13.0,...,26.6,145.0,112.0,IND,104,1,2025,2025-04-08,False,False
25415,34.0,87.0,0.391,10.0,33.0,0.303,25.0,30.0,0.833,13.0,...,31.5,165.0,109.0,PHI,122,0,2025,2025-04-09,False,False
25456,35.0,91.0,0.385,10.0,41.0,0.244,9.0,12.0,0.750,8.0,...,31.2,261.0,97.0,CHI,119,1,2025,2025-04-11,False,True
25479,46.0,90.0,0.511,16.0,37.0,0.432,11.0,17.0,0.647,6.0,...,33.1,162.0,125.0,MIA,118,1,2025,2025-04-13,True,NaN

In [9]:
# Last row (most recent game for that team) now has NaN, so replace all nulls with 2
# This will signify that the game is the most recent box-score for that team
df.loc[pd.isnull(df["target"]), "target"] = 2
# Also convert our true/false to 1/0 so possible values are 0,1,2
df["target"] = df["target"].astype(int, errors="ignore") 
# Finally, set null ft%'s to 0 when team shoots 0 fts (rare case)
df.fillna({'ft%': 0, 'ft%_max': 0, 'ft%_opp': 0, 'ft%_max_opp': 0}, inplace=True)
df.fillna({'+/-_max': 0, '+/-_max_opp': 0}, inplace=True)

In [10]:
df["won"].value_counts() # Even because always a winner

won
True     12748
False    12748
Name: count, dtype: int64

In [11]:
df["target"].value_counts() # Thirty 2s because each team has a most recent game

target
1    12734
0    12732
2       30
Name: count, dtype: int64

In [12]:
# Now, we will handle null columns since those cannot be included in the model
nulls = pd.isnull(df)

In [13]:
nulls = nulls.sum() #Find number of nulls in each column
nulls

fg          0
fga         0
fg%         0
3p          0
3pa         0
           ..
home_opp    0
season      0
date        0
won         0
target      0
Length: 145, dtype: int64

In [14]:
nulls = nulls[nulls > 0]
nulls

+/-           25496
mp_max        25496
+/-_opp       25496
mp_max_opp    25496
dtype: int64

In [15]:
#Get only the columns that are not in our nulls list from above
nulls.index
valid_columns = df.columns[~df.columns.isin(nulls.index)]
valid_columns

Index(['fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%', 'orb',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=141)

In [16]:
nulls.index

Index(['+/-', 'mp_max', '+/-_opp', 'mp_max_opp'], dtype='object')

In [17]:
df = df[valid_columns].copy()

In [18]:
df
print(list(df.columns))

['fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'ts%', 'efg%', '3par', 'ftr', 'orb%', 'drb%', 'trb%', 'ast%', 'stl%', 'blk%', 'tov%', 'usg%', 'ortg', 'drtg', 'fg_max', 'fga_max', 'fg%_max', '3p_max', '3pa_max', '3p%_max', 'ft_max', 'fta_max', 'ft%_max', 'orb_max', 'drb_max', 'trb_max', 'ast_max', 'stl_max', 'blk_max', 'tov_max', 'pf_max', 'pts_max', '+/-_max', 'ts%_max', 'efg%_max', '3par_max', 'ftr_max', 'orb%_max', 'drb%_max', 'trb%_max', 'ast%_max', 'stl%_max', 'blk%_max', 'tov%_max', 'usg%_max', 'ortg_max', 'drtg_max', 'team', 'total', 'home', 'mp_opp', 'fg_opp', 'fga_opp', 'fg%_opp', '3p_opp', '3pa_opp', '3p%_opp', 'ft_opp', 'fta_opp', 'ft%_opp', 'orb_opp', 'drb_opp', 'trb_opp', 'ast_opp', 'stl_opp', 'blk_opp', 'tov_opp', 'pf_opp', 'pts_opp', 'ts%_opp', 'efg%_opp', '3par_opp', 'ftr_opp', 'orb%_opp', 'drb%_opp', 'trb%_opp', 'ast%_opp', 'stl%_opp', 'blk%_opp', 'tov%_opp', 'usg%_opp', 'ortg_opp', 'drtg_opp', 'fg_max_opp', 'fga_max_opp', 'fg%_max_opp', '3p_max_opp', '3pa_max_opp', '3p%_max_opp', 'ft_max_opp', 'fta_max_opp', 'ft%_max_opp', 'orb_max_opp', 'drb_max_opp', 'trb_max_opp', 'ast_max_opp', 'stl_max_opp', 'blk_max_opp', 'tov_max_opp', 'pf_max_opp', 'pts_max_opp', '+/-_max_opp', 'ts%_max_opp', 'efg%_max_opp', '3par_max_opp', 'ftr_max_opp', 'orb%_max_opp', 'drb%_max_opp', 'trb%_max_opp', 'ast%_max_opp', 'stl%_max_opp', 'blk%_max_opp', 'tov%_max_opp', 'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp', 'home_opp', 'season', 'date', 'won', 'target']

In [19]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier
from sklearn.preprocessing import MinMaxScaler

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)
# Forward Direction means start at 0 features, and select best feature until 30, can test backwards too
sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [20]:
# Grab columns we can't scale since they're just context
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

In [21]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [22]:
# Scales our values to fall between 0 and 1 to make ridge regression better
scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [23]:
df
print(list(df.columns))

['fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'ts%', 'efg%', '3par', 'ftr', 'orb%', 'drb%', 'trb%', 'ast%', 'stl%', 'blk%', 'tov%', 'usg%', 'ortg', 'drtg', 'fg_max', 'fga_max', 'fg%_max', '3p_max', '3pa_max', '3p%_max', 'ft_max', 'fta_max', 'ft%_max', 'orb_max', 'drb_max', 'trb_max', 'ast_max', 'stl_max', 'blk_max', 'tov_max', 'pf_max', 'pts_max', '+/-_max', 'ts%_max', 'efg%_max', '3par_max', 'ftr_max', 'orb%_max', 'drb%_max', 'trb%_max', 'ast%_max', 'stl%_max', 'blk%_max', 'tov%_max', 'usg%_max', 'ortg_max', 'drtg_max', 'team', 'total', 'home', 'mp_opp', 'fg_opp', 'fga_opp', 'fg%_opp', '3p_opp', '3pa_opp', '3p%_opp', 'ft_opp', 'fta_opp', 'ft%_opp', 'orb_opp', 'drb_opp', 'trb_opp', 'ast_opp', 'stl_opp', 'blk_opp', 'tov_opp', 'pf_opp', 'pts_opp', 'ts%_opp', 'efg%_opp', '3par_opp', 'ftr_opp', 'orb%_opp', 'drb%_opp', 'trb%_opp', 'ast%_opp', 'stl%_opp', 'blk%_opp', 'tov%_opp', 'usg%_opp', 'ortg_opp', 'drtg_opp', 'fg_max_opp', 'fga_max_opp', 'fg%_max_opp', '3p_max_opp', '3pa_max_opp', '3p%_max_opp', 'ft_max_opp', 'fta_max_opp', 'ft%_max_opp', 'orb_max_opp', 'drb_max_opp', 'trb_max_opp', 'ast_max_opp', 'stl_max_opp', 'blk_max_opp', 'tov_max_opp', 'pf_max_opp', 'pts_max_opp', '+/-_max_opp', 'ts%_max_opp', 'efg%_max_opp', '3par_max_opp', 'ftr_max_opp', 'orb%_max_opp', 'drb%_max_opp', 'trb%_max_opp', 'ast%_max_opp', 'stl%_max_opp', 'blk%_max_opp', 'tov%_max_opp', 'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp', 'home_opp', 'season', 'date', 'won', 'target']

In [24]:
#NOTE: Don't need to do anymore since predicting this way without rolling is poor (will also comment out next few lines)
#sfs.fit(df[selected_columns], df["target"])

In [25]:
# Pick 30 best features
#predictors = list(selected_columns[sfs.get_support()])
#predictors

In [26]:
# Backtesting will let us test our model's accuracy by splitting data up by season and use past seasons to predict another one
# (i.e. using 2016,2017 to predict 2018's games and seeing if results are accurate to what really happened in 2018)
def backtest(df, model, predictors, detailed, start=2, step=1):
    all_predictions = [] #List of dataframes for actual vs prediction results for each season
    
    #Get list of all unique seasons
    seasons = sorted(df["season"].unique())
    #Loop through each season, starting at 2 (so 2018 will be the first season we predict for)
    for i in range(start, len(seasons), step):
        season = seasons[i]
        # Grab only df data from 2016 (our oldest data) to one before current iterating season for training model
        train = df[df["season"] < season] 
        # Grab all data for current iterating season that we will try to predict
        test = df[df["season"] == season] 
        #Fit model, feeding in the features we want to train from, and the correct results from the train set
        model.fit(train[predictors], train["target"])
        #After fitting, predict current iterating season by passing in the predictor values 
        preds = model.predict(test[predictors])
        #Convert array to a pandas series that labels each prediction by it's dataframe index
        preds = pd.Series(preds, index=test.index)
        #Now, preds is a series of 0's and 1's of whether or not team is predicted to win that index's game
        #Combine actual results (the target of test set) with predictions and rename for clarity
        if detailed:
            combined = pd.concat([test["target"], preds, test["team_x"], test["team_y"], test["date"], test["date_next"]], axis=1)
            combined.columns = ["actual", "prediction", "team1", "team2", "last played date", "predict game date"]
        else:
            combined = pd.concat([test["target"], preds], axis=1)
            combined.columns = ["actual", "prediction"]
        #Save actual/predictions for this season
        all_predictions.append(combined)
        
    #Concat all season's together and return
    return pd.concat(all_predictions)

In [27]:
# Pass in ridge classifier as our model along with dataframe and predictors
#predictions = backtest(df, rr, predictors, detailed = False)

In [28]:
#predictions

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
#predictions = predictions[predictions["actual"] != 2] # Remove the 2s 
#accuracy_score(predictions["actual"], predictions["prediction"])

In [31]:
#Group by home, and then calculate % of time team won when they were home (number of won rows versus total number of rows)
#df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

In [32]:
#We see how our prediction was worse than just guessing by home/away
#To beat this baseline percentage, we will use a team's last 10 games instead of 1 game, and then run prediction again to improve %
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [33]:
df_rolling

,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.391304,0.529412,0.276190,0.413793,0.378788,0.491686,0.454545,0.406250,0.769,0.793103,...,0.071,0.550314,0.151282,0.800948,0.473118,0.267857,1.0,True,DET,2016
1,0.391304,0.323529,0.433333,0.275862,0.348485,0.351544,0.272727,0.234375,0.800,0.241379,...,0.047,0.300839,0.020513,0.203791,0.290323,0.375000,0.0,False,ATL,2016
2,0.413043,0.500000,0.321429,0.310345,0.378788,0.368171,0.227273,0.265625,0.588,0.379310,...,0.140,0.509434,0.161538,0.345972,0.290323,0.294643,1.0,False,CLE,2016
3,0.391304,0.397059,0.371429,0.241379,0.227273,0.437055,0.363636,0.359375,0.696,0.241379,...,0.185,0.270440,0.089744,0.232227,0.301075,0.276786,0.0,True,CHI,2016
4,0.347826,0.338235,0.364286,0.206897,0.212121,0.395487,0.431818,0.421875,0.704,0.275862,...,0.079,0.679245,0.278205,0.554502,0.290323,0.419643,1.0,False,NOP,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25491,0.282609,0.367647,0.254762,0.379310,0.530303,0.334917,0.250000,0.281250,0.611,0.620690,...,0.140,0.371069,0.157692,0.322275,0.322581,0.258929,1.0,False,CHO,2025
25492,0.608696,0.411765,0.630952,0.586207,0.545455,0.504751,0.136364,0.156250,0.600,0.310345,...,0.158,0.283019,0.148718,0.483412,0.559140,0.366071,0.0,True,ATL,2025
25493,0.456522,0.411765,0.442857,0.517241,0.469697,0.509501,0.227273,0.234375,0.667,0.413793,...,0.095,0.323899,0.134615,0.336493,0.430108,0.473214,1.0,False,ORL,2025
25494,0.717391,0.647059,0.550000,0.517241,0.560606,0.434679,0.295455,0.234375,0.867,0.655172,...,0.109,0.222222,0.124359,0.255924,0.645161,0.294643,0.0,True,MEM,2025
25495,0.521739,0.352941,0.578571,0.379310,0.424242,0.408551,0.636364,0.500000,0.875,0.310345,...,0.025,0.149895,0.132051,0.668246,0.580645,0.482143,0.0,True,SAS,2025

In [34]:
#Team parameter is sub-set of entire rolling_df for each team/each season (i.e. ATL 2015, ATL 2016, OKC 2021)
def find_team_averages(team):
    #Rolling method groups row with previous 10 games, and then we take mean of each stat (and exclude won, team, and season)
    rolling = team[selected_columns].rolling(10).mean()
    return rolling
    
#Group by team to ensure last 10 are that team's games, and group season to ensure that we don't go back to previous season
df_rolling = df_rolling.groupby(["team", "season"], group_keys = False).apply(find_team_averages)

/tmp/ipykernel_6777/1381933995.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_rolling = df_rolling.groupby(["team", "season"], group_keys = False).apply(find_team_averages)

In [35]:
df_rolling

,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,...,trb%_max_opp,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25491,0.378261,0.385294,0.369762,0.362069,0.453030,0.370190,0.368182,0.334375,0.7425,0.355172,...,0.183004,0.380161,0.0608,0.0966,0.344025,0.266282,0.491469,0.365591,0.468750,0.6
25492,0.567391,0.445588,0.550476,0.534483,0.553030,0.452375,0.384091,0.339062,0.7683,0.389655,...,0.169627,0.289679,0.0607,0.0913,0.310063,0.174872,0.465877,0.568817,0.491964,0.6
25493,0.478261,0.388235,0.490000,0.475862,0.506061,0.435511,0.359091,0.315625,0.7916,0.400000,...,0.161842,0.467431,0.1326,0.1064,0.300839,0.123333,0.485782,0.522581,0.342857,0.5
25494,0.541304,0.470588,0.492619,0.544828,0.557576,0.462352,0.384091,0.325000,0.8126,0.400000,...,0.226206,0.332683,0.0527,0.0704,0.257757,0.183718,0.398578,0.534409,0.466071,0.6
25495,0.476087,0.408824,0.472143,0.503448,0.539394,0.437767,0.334091,0.300000,0.7486,0.303448,...,0.218421,0.289908,0.0634,0.0769,0.389727,0.278333,0.559716,0.454839,0.493750,0.5

In [36]:
#Re-name all rolling stat columns for indication, and then concat the two dataframes together, side-by-side
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols
df = pd.concat([df, df_rolling], axis = 1)

In [37]:
df = df.dropna() #Drop NaN stats from the first 10 games since they didn't have 10 games to go back of
df

,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,orb,...,trb%_max_opp_10,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10
243,0.500000,0.382353,0.521429,0.344828,0.333333,0.457245,0.272727,0.250000,0.750,0.275862,...,0.152851,0.311927,0.0628,0.0679,0.413522,0.125256,0.361611,0.410753,0.322321,0.4
249,0.630435,0.426471,0.642857,0.620690,0.515152,0.562945,0.340909,0.250000,0.938,0.206897,...,0.166667,0.412271,0.0613,0.0772,0.469497,0.220641,0.394787,0.486022,0.300893,0.5
252,0.326087,0.250000,0.411905,0.310345,0.257576,0.509501,0.522727,0.421875,0.852,0.448276,...,0.132675,0.458257,0.0699,0.1072,0.380294,0.274359,0.270616,0.437634,0.286607,0.6
255,0.282609,0.235294,0.361905,0.344828,0.348485,0.439430,0.636364,0.484375,0.903,0.344828,...,0.135965,0.398280,0.0747,0.0742,0.303564,0.131667,0.387678,0.375269,0.325893,0.5
259,0.217391,0.279412,0.233333,0.310345,0.348485,0.395487,0.386364,0.328125,0.810,0.344828,...,0.195285,0.314220,0.0620,0.0626,0.373480,0.142436,0.320379,0.392473,0.318750,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25491,0.282609,0.367647,0.254762,0.379310,0.530303,0.334917,0.250000,0.281250,0.611,0.620690,...,0.183004,0.380161,0.0608,0.0966,0.344025,0.266282,0.491469,0.365591,0.468750,0.6
25492,0.608696,0.411765,0.630952,0.586207,0.545455,0.504751,0.136364,0.156250,0.600,0.310345,...,0.169627,0.289679,0.0607,0.0913,0.310063,0.174872,0.465877,0.568817,0.491964,0.6
25493,0.456522,0.411765,0.442857,0.517241,0.469697,0.509501,0.227273,0.234375,0.667,0.413793,...,0.161842,0.467431,0.1326,0.1064,0.300839,0.123333,0.485782,0.522581,0.342857,0.5
25494,0.717391,0.647059,0.550000,0.517241,0.560606,0.434679,0.295455,0.234375,0.867,0.655172,...,0.226206,0.332683,0.0527,0.0704,0.257757,0.183718,0.398578,0.534409,0.466071,0.6
25495,0.521739,0.352941,0.578571,0.379310,0.424242,0.408551,0.636364,0.500000,0.875,0.310345,...,0.218421,0.289908,0.0634,0.0769,0.389727,0.278333,0.559716,0.454839,0.493750,0.5

In [38]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col
    
def add_col(df, col_name):
    #Use shift_col as a lambda to get the column name's next value (for that specific team group)
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

#Add columns to indicate if team will be home, who they'll face, and date
#These will be NaN on the most recent game that team played, so we'll have to manually fill it in using scraped schedule
df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

/tmp/ipykernel_6777/2506316825.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))
/tmp/ipykernel_6777/2506316825.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))
/tmp/ipykernel_6777/2506316825.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

In [39]:
#Find rows where team is CHI and list out columns (last 3 are what we will have to manually fill using schedule of next game)
df[df["team"] == "LAL"][["date", "target", "team", "season", "team_opp", "home_next", "team_opp_next", "date_next"]]

,date,target,team,season,team_opp,home_next,team_opp_next,date_next
295,2015-11-15,0,LAL,2016,DET,0.0,PHO,2015-11-16
305,2015-11-16,0,LAL,2016,PHO,1.0,TOR,2015-11-20
363,2015-11-20,0,LAL,2016,TOR,1.0,POR,2015-11-22
390,2015-11-22,0,LAL,2016,POR,0.0,GSW,2015-11-24
423,2015-11-24,0,LAL,2016,GSW,0.0,POR,2015-11-28
...,...,...,...,...,...,...,...,...
25370,2025-04-06,0,LAL,2025,OKC,0.0,OKC,2025-04-08
25391,2025-04-08,1,LAL,2025,OKC,0.0,DAL,2025-04-09
25422,2025-04-09,1,LAL,2025,DAL,1.0,HOU,2025-04-11
25452,2025-04-11,0,LAL,2025,HOU,0.0,POR,2025-04-13
25474,2025-04-13,2,LAL,2025,POR,NaN,None,None

In [40]:
# Now, we will use our future csv with future games to fill in home_next, team_opp_next, and date_next
future = pd.read_csv("future_2025.csv")
#future[future["away_abbrev"] == "MEM"]
future

,Date,Start (ET),Visitor/Neutral,Home/Neutral,home_abbrev,away_abbrev
0,2025-02-01,8:30p,Los Angeles Lakers,New York Knicks,NYK,LAL
1,2025-02-01,10:00p,Phoenix Suns,Portland Trail Blazers,POR,PHO
2,2025-02-01,8:30p,Miami Heat,San Antonio Spurs,SAS,MIA
3,2025-02-01,8:00p,Sacramento Kings,Oklahoma City Thunder,OKC,SAC
4,2025-02-01,5:00p,Atlanta Hawks,Indiana Pacers,IND,ATL
...,...,...,...,...,...,...
514,2025-04-13,1:00p,New York Knicks,Brooklyn Nets,BRK,NYK
515,2025-04-13,1:00p,Charlotte Hornets,Boston Celtics,BOS,CHO
516,2025-04-13,1:00p,Orlando Magic,Atlanta Hawks,ATL,ORL
517,2025-04-13,3:30p,Los Angeles Clippers,Golden State Warriors,GSW,LAC
518,2025-04-13,3:30p,Toronto Raptors,San Antonio Spurs,SAS,TOR

In [41]:
# Before using the future dataframe, we will drop all the games that have already been played using today's date
# If at the end of a season, this df will be empty since there is nothing else to predict
def parse_date(date_str):
    return datetime.strptime(date_str, "%Y-%m-%d").date() # We access date() method to not compare times (ruins comparison)
    
def remove_old_games(df, curr_date):
    # Drop all rows with dates before today (but keep today's date for predicting)
    df = df.drop(
        df[df["Date"].apply(parse_date) < curr_date.date()].index
    )
    return df

curr_date = datetime.today()
future = remove_old_games(future, curr_date)
future

Empty DataFrame
Columns: [Date, Start (ET), Visitor/Neutral, Home/Neutral, home_abbrev, away_abbrev]
Index: []

In [ ]:
# Now that future contains only games that have yet to be played (either today or later), we can use to fill NaN
def nearest_date(items, pivot):
    return min(items, key=lambda x: abs(x - pivot))

def parse_date(date_str):
    return datetime.strptime(date_str, "%Y-%m-%d").date()

# Takes in a row for game that requires filling in a next stat (home, team_opp, date)
def add_next_stat(target_game, stat): 
    # Get current team abbrev and date of their last played game
    team_abbrev = target_game["team"]
    last_date = datetime.strptime(target_game["date"], "%Y-%m-%d").date()
    # Use abbrev to get all the future games of the team
    next_games = future[
        (future["home_abbrev"] == team_abbrev) | (future["away_abbrev"] == team_abbrev)
    ]
    # From rows of future games for team, find the one that is closest to the last game date, using iloc to get 'first' (only) row
    next_game = next_games[
        next_games["Date"] == datetime.strftime(nearest_date(next_games["Date"].apply(parse_date), last_date), "%Y-%m-%d")
    ].iloc[0] 
    # Now that we have a series for team_abbrev's next game, check which stat was passed in and return corresponding value
    if (stat == "home_next"):
        if next_game["home_abbrev"] == team_abbrev: 
            return 1
        return 0
    if (stat == "date_next"):
        return next_game["Date"]
    if (stat == "team_opp_next"):
        if next_game["home_abbrev"] == team_abbrev:
            return next_game["away_abbrev"]
        return next_game["home_abbrev"]
    return None # Will never hit this

#Use our add_next_stat function to apply to all rows with target == 2 the three missing stats. 
df.loc[df["target"] == 2, "home_next"] = df[df["target"] == 2].apply(add_next_stat, stat="home_next", axis = 1)
df.loc[df["target"] == 2, "team_opp_next"] = df[df["target"] == 2].apply(add_next_stat, stat="team_opp_next", axis = 1)
df.loc[df["target"] == 2, "date_next"] = df[df["target"] == 2].apply(add_next_stat, stat="date_next", axis = 1)

In [43]:
#Testing new method (either way seems to work)
# df_copy = df.copy()
# dfnulls = df.index[pd.isnull(df["team_opp_next"])].tolist()

# for i in dfnulls:
#     print(i, df['team'][i], df['team_opp_next'][i])
#     #if df['team'][i] == 'CHI' or df['team'][i] == 'CHO':
#         #continue
#     firstIndxVisitor = future.index[(future['away_abbrev'] == df['team'][i])].tolist()[0]
#     firstIndxHome = future.index[(future['home_abbrev'] == df['team'][i])].tolist()[0]
#     firstIndx = min(firstIndxHome, firstIndxVisitor)
    
#     if firstIndx == firstIndxHome:
#         df.loc[i, 'team_opp_next'] = future.loc[firstIndx, 'away_abbrev']
#         df.loc[i, 'home_next'] = 1  # Home game
#     else:
#         df.loc[i, 'team_opp_next'] = future.loc[firstIndx, 'home_abbrev']
#         df.loc[i, 'home_next'] = 0  # Away game
        
#     df.loc[i, 'date_next'] = future.loc[firstIndx, 'Date']

In [44]:
# Issue here is that there may be 2 TOR-LAC and LAC-TOR rows, and then an extra LAL-LAC row. LAL-LAC will be dropped
# Since there's no LAC-LAL row that corresponds to it in the merge. So we go from 30 rows to ~24 rows and don't predict some
df[df["target"] == 2][["target", "date", "team", "home_next", "team_opp_next", "date_next"]]

       target        date team  home_next team_opp_next   date_next
25319       2  2025-04-03  ORL        1.0           ATL  2025-04-08
25350       2  2025-04-05  PHI        0.0           MIA  2025-04-07
25351       2  2025-04-05  MIN        0.0           MIL  2025-04-08
25352       2  2025-04-05  MIA        1.0           PHI  2025-04-07
25354       2  2025-04-05  LAC        1.0           SAS  2025-04-08
25355       2  2025-04-05  DET        1.0           SAC  2025-04-07
25356       2  2025-04-05  MEM        0.0           CHO  2025-04-08
25359       2  2025-04-05  DAL        1.0           LAL  2025-04-09
25360       2  2025-04-06  DEN        0.0           SAC  2025-04-09
25361       2  2025-04-06  LAL        0.0           OKC  2025-04-08
25362       2  2025-04-06  OKC        1.0           LAL  2025-04-08
25363       2  2025-04-06  NYK        1.0           BOS  2025-04-08
25364       2  2025-04-06  PHO        1.0           GSW  2025-04-08
25365       2  2025-04-06  NOP        0.0           BRK  2025-04-08
25366       2  2025-04-06  MIL        1.0           MIN  2025-04-08
25367       2  2025-04-06  GSW        0.0           PHO  2025-04-08
25368       2  2025-04-06  HOU        0.0           LAC  2025-04-09
25369       2  2025-04-06  IND        1.0           WAS  2025-04-08
25370       2  2025-04-06  ATL        0.0           ORL  2025-04-08
25371       2  2025-04-06  SAC        0.0           DET  2025-04-07
25372       2  2025-04-06  CHO        1.0           MEM  2025-04-08
25373       2  2025-04-06  CHI        0.0           CLE  2025-04-08
25374       2  2025-04-06  BRK        1.0           NOP  2025-04-08
25375       2  2025-04-06  TOR        1.0           CHO  2025-04-09
25376       2  2025-04-06  BOS        0.0           NYK  2025-04-08
25377       2  2025-04-06  WAS        0.0           IND  2025-04-08
25378       2  2025-04-06  UTA        1.0           POR  2025-04-09
25379       2  2025-04-06  SAS        0.0           LAC  2025-04-08
25380       2  2025-04-06  CLE        1.0           CHI  2025-04-08
25381       2  2025-04-06  POR        0.0           UTA  2025-04-09

In [45]:
df = df.copy() #Copy just to prevent errors
#print(list(df.columns))

In [46]:
# Now, we match a team's next game date to another team's next game date 
# Then, it'll add new columns to each row to signify their match (opponent stats will be {name}_y)
# This way, the model will know things like date_next_y (date of opponents next game) and could use it
full = df.merge(
    df[rolling_cols + ["team_opp_next", "date_next", "team"]],
    left_on=["team", "date_next"],
    right_on=["team_opp_next", "date_next"]
)

In [47]:
# Here, team_y is team_x's (the one we're analyzing) NEXT opponent, and so team_y's next opponent should match team_x
full[full["target"] == 2][["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
22511    ORL             ATL    ATL             ORL  2025-04-08
22542    PHI             MIA    MIA             PHI  2025-04-07
22543    MIN             MIL    MIL             MIN  2025-04-08
22544    MIA             PHI    PHI             MIA  2025-04-07
22546    LAC             SAS    SAS             LAC  2025-04-08
22547    DET             SAC    SAC             DET  2025-04-07
22548    MEM             CHO    CHO             MEM  2025-04-08
22551    LAL             OKC    OKC             LAL  2025-04-08
22552    OKC             LAL    LAL             OKC  2025-04-08
22553    NYK             BOS    BOS             NYK  2025-04-08
22554    PHO             GSW    GSW             PHO  2025-04-08
22555    NOP             BRK    BRK             NOP  2025-04-08
22556    MIL             MIN    MIN             MIL  2025-04-08
22557    GSW             PHO    PHO             GSW  2025-04-08
22558    IND             WAS    WAS             IND  2025-04-08
22559    ATL             ORL    ORL             ATL  2025-04-08
22560    SAC             DET    DET             SAC  2025-04-07
22561    CHO             MEM    MEM             CHO  2025-04-08
22562    CHI             CLE    CLE             CHI  2025-04-08
22563    BRK             NOP    NOP             BRK  2025-04-08
22564    BOS             NYK    NYK             BOS  2025-04-08
22565    WAS             IND    IND             WAS  2025-04-08
22566    UTA             POR    POR             UTA  2025-04-09
22567    SAS             LAC    LAC             SAS  2025-04-08
22568    CLE             CHI    CHI             CLE  2025-04-08
22569    POR             UTA    UTA             POR  2025-04-09

In [48]:
#testing problem where games are dropped
before_merge = df[df["target"] == 2][["team", "team_opp_next", "date_next"]]
after_merge = full[full["target"] == 2][["team_x", "team_opp_next_x", "date_next"]]

missing_games = before_merge[~before_merge["team"].isin(after_merge["team_x"])]
print("NOTE: The following games will not have predictions because their opponents have yet to play") 
print(missing_games)

NOTE: The following games will not have predictions because their opponents have yet to play
      team team_opp_next   date_next
25359  DAL           LAL  2025-04-09
25360  DEN           SAC  2025-04-09
25368  HOU           LAC  2025-04-09
25375  TOR           CHO  2025-04-09

In [49]:
#Now, we prepare to select features again with these new rolling averages by selecting new string columns
removed_columns = ["season", "date", "won", "target", "team", "team_opp"] 
removed_columns = list(full.columns[full.dtypes=="object"]) + removed_columns

In [50]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [51]:
#Get all columns that aren't removed (includes our new _x and _y merge cols)
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [52]:
#Use feature selector to get 30 best again
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [53]:
#Get Support function returns array of bools for wehther or not feature was included, so index by trues
predictors = list(selected_columns[sfs.get_support()])

In [54]:
predictors

['orb',
 'efg%',
 'usg%',
 '3p_max',
 'home',
 'blk%_opp',
 'usg%_opp',
 'pts_max_opp',
 'orb%_max_opp',
 'usg%_10_x',
 'pts_max_10_x',
 '+/-_max_10_x',
 'drb%_max_10_x',
 '3p%_opp_10_x',
 'blk_opp_10_x',
 'ts%_opp_10_x',
 'usg%_opp_10_x',
 'stl_max_opp_10_x',
 '+/-_max_opp_10_x',
 'ast%_max_opp_10_x',
 'home_next',
 'usg%_10_y',
 'fg_max_10_y',
 'pts_max_10_y',
 '+/-_max_10_y',
 'ortg_max_10_y',
 'stl%_opp_10_y',
 'usg%_opp_10_y',
 '+/-_max_opp_10_y',
 'ftr_max_opp_10_y']

In [55]:
predictions = backtest(full, rr, predictors, detailed=True)

In [56]:
real_predictions = predictions[predictions["actual"] == 2]
#Get new accuracy score
predictions = predictions[predictions["actual"] != 2] # Remove the 2s for accuracy score
accuracy_score(predictions["actual"], predictions["prediction"])

0.6374321374601221

In [57]:
copy = real_predictions
real_predictions

       actual  prediction team1 team2 last played date predict game date
22511       2           1   ORL   ATL       2025-04-03        2025-04-08
22542       2           0   PHI   MIA       2025-04-05        2025-04-07
22543       2           1   MIN   MIL       2025-04-05        2025-04-08
22544       2           1   MIA   PHI       2025-04-05        2025-04-07
22546       2           1   LAC   SAS       2025-04-05        2025-04-08
22547       2           1   DET   SAC       2025-04-05        2025-04-07
22548       2           1   MEM   CHO       2025-04-05        2025-04-08
22551       2           0   LAL   OKC       2025-04-06        2025-04-08
22552       2           1   OKC   LAL       2025-04-06        2025-04-08
22553       2           0   NYK   BOS       2025-04-06        2025-04-08
22554       2           1   PHO   GSW       2025-04-06        2025-04-08
22555       2           0   NOP   BRK       2025-04-06        2025-04-08
22556       2           1   MIL   MIN       2025-04-06        2025-04-08
22557       2           1   GSW   PHO       2025-04-06        2025-04-08
22558       2           1   IND   WAS       2025-04-06        2025-04-08
22559       2           0   ATL   ORL       2025-04-06        2025-04-08
22560       2           0   SAC   DET       2025-04-06        2025-04-07
22561       2           0   CHO   MEM       2025-04-06        2025-04-08
22562       2           0   CHI   CLE       2025-04-06        2025-04-08
22563       2           0   BRK   NOP       2025-04-06        2025-04-08
22564       2           1   BOS   NYK       2025-04-06        2025-04-08
22565       2           0   WAS   IND       2025-04-06        2025-04-08
22566       2           0   UTA   POR       2025-04-06        2025-04-09
22567       2           0   SAS   LAC       2025-04-06        2025-04-08
22568       2           0   CLE   CHI       2025-04-06        2025-04-08
22569       2           1   POR   UTA       2025-04-06        2025-04-09

In [58]:
# Create a new column with sorted team pairs
real_predictions['team_pair'] = real_predictions.apply(lambda row: '_'.join(sorted([row['team1'], row['team2']])), axis=1)

# Sort the DataFrame by the team_pair column (and optionally by date)
df_sorted = real_predictions.sort_values(by=['team_pair', 'predict game date'])

# Drop the temporary column if you don't need it
df_sorted = df_sorted.drop(columns=['team_pair'])

# Reset index if desired
df_sorted = df_sorted.reset_index(drop=True)

In [59]:
df_sorted

    actual  prediction team1 team2 last played date predict game date
0        2           1   ORL   ATL       2025-04-03        2025-04-08
1        2           0   ATL   ORL       2025-04-06        2025-04-08
2        2           0   NYK   BOS       2025-04-06        2025-04-08
3        2           1   BOS   NYK       2025-04-06        2025-04-08
4        2           0   NOP   BRK       2025-04-06        2025-04-08
5        2           0   BRK   NOP       2025-04-06        2025-04-08
6        2           0   CHI   CLE       2025-04-06        2025-04-08
7        2           0   CLE   CHI       2025-04-06        2025-04-08
8        2           1   MEM   CHO       2025-04-05        2025-04-08
9        2           0   CHO   MEM       2025-04-06        2025-04-08
10       2           1   DET   SAC       2025-04-05        2025-04-07
11       2           0   SAC   DET       2025-04-06        2025-04-07
12       2           1   PHO   GSW       2025-04-06        2025-04-08
13       2           1   GSW   PHO       2025-04-06        2025-04-08
14       2           1   IND   WAS       2025-04-06        2025-04-08
15       2           0   WAS   IND       2025-04-06        2025-04-08
16       2           1   LAC   SAS       2025-04-05        2025-04-08
17       2           0   SAS   LAC       2025-04-06        2025-04-08
18       2           0   LAL   OKC       2025-04-06        2025-04-08
19       2           1   OKC   LAL       2025-04-06        2025-04-08
20       2           0   PHI   MIA       2025-04-05        2025-04-07
21       2           1   MIA   PHI       2025-04-05        2025-04-07
22       2           1   MIN   MIL       2025-04-05        2025-04-08
23       2           1   MIL   MIN       2025-04-06        2025-04-08
24       2           0   UTA   POR       2025-04-06        2025-04-09
25       2           1   POR   UTA       2025-04-06        2025-04-09